import Head from 'next/head'
import {Button, Radio} from 'antd'



export default function Home() {
  return (
    <div>
      <Head>
        <title>FullStack SpringBoot Next App</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <Button type="primary">Hello</Button>
      <br/>
      <Radio.Group value="large">
        <Radio.Button value="large">Large</Radio.Button>
        <Radio.Button value="default">Default</Radio.Button>
        <Radio.Button value="small">Small</Radio.Button>
      </Radio.Group>
    </div>
  )
}
